services:
  app:
    image: ${DOCKER_IMAGE_NAME:-tsuz-web-main}:${APP_VERSION:-local}
    container_name: ${CONTAINER_NAME:-tsuz-web-main}
    build:
      context: .
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/api}
        VITE_MFE_APP_ENTRY: ${VITE_MFE_APP_ENTRY:-//localhost:7201}
        VITE_APP_ENV: ${APP_ENV:-local}
    environment:
      APP_ENV: ${APP_ENV:-local}
    ports:
      - "${APP_PORT:-7200}:80"
    restart: unless-stopped
